# Generated by Django 3.2.7 on 2021-11-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='src/textpage/static/textpage/image1/', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='texts',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='src/textpage/static/textpage/image2/', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='texts',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='src/textpage/static/textpage/image3/', verbose_name='プロフィール画像'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='src/users/static/users/image/', verbose_name='プロフィール画像'),
        ),
    ]
