# Generated by Django 3.2.8 on 2021-11-12 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211112_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='text_id',
            field=models.UUIDField(default=uuid.UUID('a07b4318-8846-4003-a959-1459f97d19d3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
