# Generated by Django 3.2.8 on 2021-11-12 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_texts_text_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
