# Generated by Django 3.2.8 on 2021-11-13 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_texts_text_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
