# Generated by Django 3.2.8 on 2021-11-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211113_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='text_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
