# Generated by Django 3.2.8 on 2021-12-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_texts_text_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcom',
            name='tcom_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
