# Generated by Django 3.2.8 on 2021-12-13 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_messages_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('ToUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.texts')),
            ],
        ),
    ]
