# Generated by Django 3.2.8 on 2021-12-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_classes_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classform',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='method_eval',
            field=models.TextField(),
        ),
    ]
