# Generated by Django 3.2.8 on 2021-12-13 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20211213_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='credit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
