# Generated by Django 3.2.8 on 2021-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_messages_reading_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcom',
            name='exhibitor_or_all',
            field=models.BooleanField(default=False),
        ),
    ]
