# Generated by Django 3.2.8 on 2021-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_tcom_exhibitor_or_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='src/textpage/static/textpage/image2/', verbose_name='商品画像２'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='src/textpage/static/textpage/image3/', verbose_name='商品画像３'),
        ),
    ]
