# Generated by Django 3.2.8 on 2021-12-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccom',
            name='ccom_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cevals',
            name='ceval_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uevals',
            name='ueval_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
